project:
  type: website

website:
  title: "Statistical Computing (BSPH 140.776)"
  description: "test test"
  navbar:
    right:
      - text: "Home"
        file: index.qmd
      - text: "General Information"
        menu:
        - text: "Syllabus"
          href: syllabus.qmd
        - text: "Schedule"
          href: schedule.qmd
      - text: "Course Materials"
        menu: 
        - text: "Lectures"
          href: lectures.qmd
        - text: "Projects"
          href: projects.qmd
        - text: "Resources"
          href: resources.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: simplex
    toc: true
    css: styles.css

editor: visual

execute:
  freeze: auto
